"""The email-confirmation gate.

Two things are worth testing here, and the second is the one that matters more.

The first is the rule itself: an unconfirmed account is refused, a confirmed one
is not, and the refusal is switchable for a deployment whose mail is not yet
delivering.

The second is that the rule is actually *wired in*. `apps/api/basivo_orch/auth/`
is generated by basivo-auth, and `copier recopy` overwrites it — which has
already silently removed a local edit once before. A gate nobody is behind
passes every test about the gate and protects nothing, so the last test asserts
the wiring rather than the behaviour.
"""

from __future__ import annotations

import os
import uuid

import pytest

# Must precede any app import: several modules build Settings at import time.
os.environ.setdefault("ENVIRONMENT", "test")
os.environ.setdefault("DEBUG", "false")
os.environ.setdefault("SECRET_KEY", "test-secret-key-" + "a" * 40)
os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/15")
os.environ.setdefault("RATE_LIMIT_ENABLED", "false")

from fastapi import HTTPException  # noqa: E402

from basivo_orch.auth.authz import Permission, require  # noqa: E402
from basivo_orch.auth.models import User  # noqa: E402
from basivo_orch.config import get_settings  # noqa: E402
from basivo_orch.gate import current_app_user, gate_is_active  # noqa: E402


def make_user(*, verified: bool) -> User:
    return User(
        id=uuid.uuid4(),
        email="ada@example.com",
        hashed_password="x",  # noqa: S106 — never verified; the gate runs after auth.
        is_active=True,
        is_verified=verified,
    )


@pytest.fixture(autouse=True)
def _clear_settings_cache():
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


async def test_confirmed_user_passes():
    user = make_user(verified=True)
    assert await current_app_user(user) is user


async def test_unconfirmed_user_is_refused(monkeypatch):
    monkeypatch.setattr("basivo_orch.gate.email_is_deliverable", lambda: True)
    with pytest.raises(HTTPException) as raised:
        await current_app_user(make_user(verified=False))

    assert raised.value.status_code == 403
    # The browser routes on the header, not on the prose: a message is for a
    # person to read and a translation away from breaking the redirect.
    assert raised.value.headers == {"X-Email-Verification-Required": "true"}


async def test_gate_can_be_turned_off_for_a_deployment_without_mail(monkeypatch):
    monkeypatch.setenv("REQUIRE_VERIFIED_EMAIL", "false")
    get_settings.cache_clear()

    user = make_user(verified=False)
    assert await current_app_user(user) is user


async def test_gate_stands_down_when_email_cannot_be_delivered(monkeypatch):
    """The regression that locked a real account out of its own workspace.

    With the gate on and no webhook configured, sign-in worked, the wall
    appeared, and "resend" reported success because the API answers 202 whether
    or not anything was sent. Nothing could ever arrive, so the account was
    stuck. Demanding proof the user has no way to produce is an outage wearing
    a security control's clothes.
    """
    monkeypatch.setenv("REQUIRE_VERIFIED_EMAIL", "true")
    monkeypatch.setattr("basivo_orch.gate.email_is_deliverable", lambda: False)
    get_settings.cache_clear()

    assert gate_is_active() is False
    user = make_user(verified=False)
    assert await current_app_user(user) is user


async def test_gate_enforces_once_email_works(monkeypatch):
    monkeypatch.setenv("REQUIRE_VERIFIED_EMAIL", "true")
    monkeypatch.setattr("basivo_orch.gate.email_is_deliverable", lambda: True)
    get_settings.cache_clear()

    assert gate_is_active() is True
    with pytest.raises(HTTPException):
        await current_app_user(make_user(verified=False))


def test_require_is_actually_behind_the_gate():
    """Regression guard for `copier recopy` reverting the local edit.

    If this fails, `authz.py` has been regenerated and every org-scoped route —
    flows, runs, analytics, keys — is open to unconfirmed accounts again. See
    docs/generated-code-edits.md.
    """
    import inspect

    dependency = require(Permission.FLOW_READ)
    parameter = inspect.signature(dependency).parameters["user"]

    assert parameter.default.dependency is current_app_user, (
        "authz.require() no longer depends on current_app_user — the email gate "
        "is bypassed. Re-apply the edit listed in docs/generated-code-edits.md."
    )
