terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }

  # State is local. That is fine for one operator and one environment, and it
  # is the reason no secret is generated by Terraform: everything sensitive is
  # created on the instance itself and never enters this state file.
  # A second operator means moving this to an S3 backend with locking.
}

provider "aws" {
  region  = var.region
  profile = var.profile

  default_tags {
    tags = {
      Project     = "basivo-orch"
      Environment = "beta"
      ManagedBy   = "terraform"
    }
  }
}
