"""add flows, runs and the node execution log

Revision ID: 41c81d9c9eb4
Revises: c588336914fd
Create Date: 2026-08-08 23:48:40.949017
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '41c81d9c9eb4'
down_revision: str | None = 'c588336914fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index('ix_api_key_org_active', 'api_key', ['organization_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_api_key_organization_id'), 'api_key', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_key_prefix'), 'api_key', ['prefix'], unique=False)
    op.create_table('flow',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_version_id', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('created_by', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_version_id'], ['flow_version.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_flow_org_slug')
    )
    op.create_index('ix_flow_org_updated', 'flow', ['organization_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_flow_organization_id'), 'flow', ['organization_id'], unique=False)
    op.create_table('flow_version',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('flow_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'version', name='uq_flow_version')
    )
    op.create_index(op.f('ix_flow_version_flow_id'), 'flow_version', ['flow_id'], unique=False)
    op.create_table('run',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('flow_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('flow_version_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'WEBHOOK', 'SCHEDULE', 'API', name='triggerkind', native_enum=False, length=16), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('started_by', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_version_id'], ['flow_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'idempotency_key', name='uq_run_idempotency')
    )
    op.create_index('ix_run_flow_created', 'run', ['flow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_run_flow_id'), 'run', ['flow_id'], unique=False)
    op.create_index('ix_run_org_status', 'run', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_run_organization_id'), 'run', ['organization_id'], unique=False)
    op.create_index(op.f('ix_run_status'), 'run', ['status'], unique=False)
    op.create_table('node_execution',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('node_id', sa.String(length=80), nullable=False),
    sa.Column('node_type', sa.String(length=80), nullable=False),
    sa.Column('node_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='nodestatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_exec_run', 'node_execution', ['run_id', 'started_at'], unique=False)
    op.create_index('ix_node_exec_type_status', 'node_execution', ['node_type', 'status'], unique=False)
    op.create_index(op.f('ix_node_execution_node_type'), 'node_execution', ['node_type'], unique=False)
    op.create_index(op.f('ix_node_execution_run_id'), 'node_execution', ['run_id'], unique=False)
    op.create_table('run_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_event_seq')
    )
    op.create_index(op.f('ix_run_event_run_id'), 'run_event', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_event_run_id'), table_name='run_event')
    op.drop_table('run_event')
    op.drop_index(op.f('ix_node_execution_run_id'), table_name='node_execution')
    op.drop_index(op.f('ix_node_execution_node_type'), table_name='node_execution')
    op.drop_index('ix_node_exec_type_status', table_name='node_execution')
    op.drop_index('ix_node_exec_run', table_name='node_execution')
    op.drop_table('node_execution')
    op.drop_index(op.f('ix_run_status'), table_name='run')
    op.drop_index(op.f('ix_run_organization_id'), table_name='run')
    op.drop_index('ix_run_org_status', table_name='run')
    op.drop_index(op.f('ix_run_flow_id'), table_name='run')
    op.drop_index('ix_run_flow_created', table_name='run')
    op.drop_table('run')
    op.drop_index(op.f('ix_flow_version_flow_id'), table_name='flow_version')
    op.drop_table('flow_version')
    op.drop_index(op.f('ix_flow_organization_id'), table_name='flow')
    op.drop_index('ix_flow_org_updated', table_name='flow')
    op.drop_table('flow')
    op.drop_index(op.f('ix_api_key_prefix'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_organization_id'), table_name='api_key')
    op.drop_index('ix_api_key_org_active', table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
