"""add credential table

Revision ID: 4e19c988ff3f
Revises: 41c81d9c9eb4
Create Date: 2026-08-12 02:00:55.669071

Autogenerate also proposed adding `flow.published_version_id`'s foreign key to
`flow_version.id` — pre-existing drift on this dev database (the FK is in the
model and in migration 41c81d9c9eb4's `upgrade()`, but is absent from the live
table; something about that migration's apply did not create it). Left out of
this migration deliberately: it is unrelated to credentials, and a schema fix
discovered as a side effect belongs in its own reviewable migration, not
bundled into this one.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4e19c988ff3f"
down_revision: str | None = "41c81d9c9eb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credential",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=48), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("base_url", sa.String(length=300), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_credential_org_name"),
    )
    op.create_index(
        "ix_credential_org_provider", "credential", ["organization_id", "provider"], unique=False
    )
    op.create_index(
        op.f("ix_credential_organization_id"), "credential", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_credential_provider"), "credential", ["provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credential_provider"), table_name="credential")
    op.drop_index(op.f("ix_credential_organization_id"), table_name="credential")
    op.drop_index("ix_credential_org_provider", table_name="credential")
    op.drop_table("credential")
    # ### end Alembic commands ###
