"""worker queue: run lease columns and flow schedules

Revision ID: 9fd26cc8c58d
Revises: b904b73fe0e4
Create Date: 2026-08-15 13:26:55.221106
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9fd26cc8c58d"
down_revision: str | None = "b904b73fe0e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flow_schedule",
        sa.Column("flow_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("cron", sa.String(length=120), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("flow_id"),
    )
    op.create_index("ix_flow_schedule_due", "flow_schedule", ["next_run_at"], unique=False)
    op.create_index(
        op.f("ix_flow_schedule_next_run_at"), "flow_schedule", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_flow_schedule_organization_id"), "flow_schedule", ["organization_id"], unique=False
    )
    op.add_column("run", sa.Column("worker_id", sa.String(length=64), nullable=True))
    op.add_column("run", sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("run", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("ix_run_queue", "run", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_queue", table_name="run")
    op.drop_column("run", "heartbeat_at")
    op.drop_column("run", "claimed_at")
    op.drop_column("run", "worker_id")
    op.drop_index(op.f("ix_flow_schedule_organization_id"), table_name="flow_schedule")
    op.drop_index(op.f("ix_flow_schedule_next_run_at"), table_name="flow_schedule")
    op.drop_index("ix_flow_schedule_due", table_name="flow_schedule")
    op.drop_table("flow_schedule")
    # ### end Alembic commands ###
