"""artifacts for rendered files

Revision ID: b3a098261fb4
Revises: 9fd26cc8c58d
Create Date: 2026-08-20 00:19:07.190478
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "b3a098261fb4"
down_revision: str | None = "9fd26cc8c58d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("node_id", sa.String(length=120), nullable=True),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifact_org_created", "artifact", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_organization_id"), "artifact", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_artifact_run_id"), "artifact", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_run_id"), table_name="artifact")
    op.drop_index(op.f("ix_artifact_organization_id"), table_name="artifact")
    op.drop_index("ix_artifact_org_created", table_name="artifact")
    op.drop_table("artifact")
    # ### end Alembic commands ###
