"""cascade run flow_version_id on flow delete

Two constraints, one story: what happens to the flow family on delete.

- `run.flow_version_id` was RESTRICT, which made deleting any flow that had
  ever run impossible — the version rows go first and the runs still pointed
  at them, so every delete 500'd. Runs are meaningless without their flow;
  they cascade with it.
- `flow.published_version_id`'s FK (SET NULL) was in migration
  41c81d9c9eb4's code but is absent from databases that ran it — the
  `use_alter` add appears not to have applied. Deliberately skipped in the
  credentials migration as unrelated; included here because a dangling
  published_version_id is this same deletion story.

Revision ID: b904b73fe0e4
Revises: 4e19c988ff3f
Create Date: 2026-08-15 01:20:47.480911
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b904b73fe0e4"
down_revision: str | None = "4e19c988ff3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_flow_published_version",
        "flow",
        "flow_version",
        ["published_version_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.drop_constraint(op.f("run_flow_version_id_fkey"), "run", type_="foreignkey")
    op.create_foreign_key(
        "fk_run_flow_version",
        "run",
        "flow_version",
        ["flow_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("fk_run_flow_version", "run", type_="foreignkey")
    op.create_foreign_key(
        op.f("run_flow_version_id_fkey"),
        "run",
        "flow_version",
        ["flow_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint("fk_flow_published_version", "flow", type_="foreignkey")
