"""bot session

Revision ID: ca79b5b80dbd
Revises: 61d1f85e6534
Create Date: 2026-08-22 20:58:58.823080
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "ca79b5b80dbd"
down_revision: str | None = "61d1f85e6534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_session",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("flow_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "photos",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status_message_id", sa.Integer(), nullable=True),
        sa.Column("last_video_artifact_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("spend_usd", sa.Float(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_video_artifact_id"], ["artifact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_id", "chat_id", name="uq_bot_session_chat"),
    )
    op.create_index(
        op.f("ix_bot_session_organization_id"), "bot_session", ["organization_id"], unique=False
    )
    op.create_index("ix_bot_session_sweep", "bot_session", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bot_session_sweep", table_name="bot_session")
    op.drop_index(op.f("ix_bot_session_organization_id"), table_name="bot_session")
    op.drop_table("bot_session")
    # ### end Alembic commands ###
