"""agent memory

Revision ID: f310f48008dc
Revises: b3a098261fb4
Create Date: 2026-08-20 15:47:47.203733
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f310f48008dc"
down_revision: str | None = "b3a098261fb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_memory",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column(
            "turns",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "scope", "subject", name="uq_agent_memory_scope"),
    )
    op.create_index(
        op.f("ix_agent_memory_organization_id"), "agent_memory", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_agent_memory_updated", "agent_memory", ["organization_id", "updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_memory_updated", table_name="agent_memory")
    op.drop_index(op.f("ix_agent_memory_organization_id"), table_name="agent_memory")
    op.drop_table("agent_memory")
    # ### end Alembic commands ###
